# Generated by Django 5.2.17 on 2026-09-07 19:40

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CampusLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('street_address', models.CharField(max_length=200)),
                ('arrival_note', models.CharField(blank=True, help_text='e.g. Main entrance, ground floor lobby.', max_length=200)),
                ('is_indoor', models.BooleanField(default=True)),
                ('capacity', models.PositiveSmallIntegerField(default=8, help_text='Largest squad this location can comfortably seat.', validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(50)])),
                ('is_approved', models.BooleanField(default=True, help_text='Unapprove to stop scheduling here without losing history.')),
            ],
            options={
                'verbose_name': 'Campus location',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('category', models.CharField(choices=[('HOBBY', 'Hobby / Interest'), ('RSO', 'Registered Student Organization'), ('ACTIVITY', 'Meeting activity')], max_length=10)),
                ('is_active', models.BooleanField(default=True, help_text="Retire an option without deleting students' history.")),
            ],
            options={
                'ordering': ['category', 'name'],
                'constraints': [models.UniqueConstraint(fields=('name', 'category'), name='uniq_interest_name_per_category')],
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connection_type', models.CharField(choices=[('FRIEND', 'Friend Connect (1-on-1)'), ('SQUAD', 'Squad Connect (4-8 students)')], max_length=10)),
                ('week_start', models.DateField(help_text='Monday of the matching week this experience belongs to.')),
                ('scheduled_for', models.DateTimeField()),
                ('status', models.CharField(choices=[('PROPOSED', 'Proposed to participants'), ('CONFIRMED', 'Confirmed by participants'), ('COMPLETED', 'Meeting completed'), ('CANCELLED', 'Cancelled')], default='PROPOSED', max_length=10)),
                ('check_in_code', models.CharField(help_text='Short code shown on Screen 8, e.g. QC-4827.', max_length=12, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matches', to='connect.campuslocation')),
                ('suggested_activity', models.ForeignKey(blank=True, limit_choices_to={'category': 'ACTIVITY'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggested_for_matches', to='connect.interest')),
            ],
            options={
                'verbose_name_plural': 'Matches',
                'ordering': ['-week_start', '-scheduled_for'],
            },
        ),
        migrations.CreateModel(
            name='MatchParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.CharField(choices=[('PENDING', 'Awaiting response'), ('ACCEPTED', 'Accepted / attendance confirmed'), ('DECLINED', 'Declined')], default='PENDING', max_length=10)),
                ('compatibility_score', models.DecimalField(decimal_places=2, default=0, help_text='0-100 fit score against the rest of this match.', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('match_reason', models.CharField(blank=True, help_text='Human-readable reasons, e.g. Basketball, Gaming, Coffee.', max_length=250)),
                ('checked_in_at', models.DateTimeField(blank=True, help_text='Set when the student enters the code on Screen 8.', null=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='connect.match')),
            ],
            options={
                'verbose_name': 'Match participant',
                'ordering': ['match', '-compatibility_score', 'profile'],
            },
        ),
        migrations.CreateModel(
            name='ExperienceFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(help_text='Overall 1-5 star rating of the experience.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('enjoyed_conversation', models.BooleanField(default=False)),
                ('enjoyed_shared_interests', models.BooleanField(default=False)),
                ('enjoyed_activity', models.BooleanField(default=False)),
                ('felt_comfortable', models.BooleanField(default=False)),
                ('wants_to_stay_connected', models.BooleanField(default=False, help_text='Mutual opt-in: a connection forms only if both sides agree.')),
                ('private_note', models.TextField(blank=True, help_text='Never shown to other participants.')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('participant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='connect.matchparticipant')),
            ],
            options={
                'verbose_name': 'Experience feedback',
                'verbose_name_plural': 'Experience feedback',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='ProfileInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False, help_text='Starred interest, weighted more heavily when matching.')),
                ('selected_at', models.DateTimeField(auto_now_add=True)),
                ('interest', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='profile_links', to='connect.interest')),
            ],
            options={
                'verbose_name': 'Profile interest',
                'ordering': ['profile', '-is_primary', 'interest'],
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('net_id', models.CharField(help_text='University NetID, e.g. jordan4. One profile per NetID.', max_length=32, unique=True)),
                ('illinois_email', models.EmailField(help_text='illinois.edu address returned by SSO.', max_length=254, unique=True)),
                ('full_name', models.CharField(max_length=120)),
                ('college', models.CharField(help_text='e.g. Grainger College of Engineering.', max_length=120)),
                ('department', models.CharField(blank=True, help_text='Optional major or program, e.g. Computer Science.', max_length=120)),
                ('part_time_job', models.CharField(blank=True, help_text='Optional on/near-campus job used as a soft matching signal.', max_length=120)),
                ('preferred_connection', models.CharField(choices=[('FRIEND', 'Friend Connect (1-on-1)'), ('SQUAD', 'Squad Connect (4-8 students)')], default='FRIEND', max_length=10)),
                ('social_energy', models.PositiveSmallIntegerField(choices=[(1, 'Quiet / Low-key'), (2, 'Somewhat quiet'), (3, 'Balanced'), (4, 'Fairly social'), (5, 'Very social')], default=3)),
                ('conversation_style', models.CharField(choices=[('CASUAL', 'Casual conversations'), ('DEEP', 'Deep conversations'), ('ACTIVITY', 'Activity-focused')], default='CASUAL', max_length=10)),
                ('group_preference', models.CharField(choices=[('ONE', 'One person'), ('SMALL', 'Small group (3-5)'), ('EITHER', 'Either')], default='EITHER', max_length=10)),
                ('prefers_same_age', models.BooleanField(default=True, help_text='Screen 4: comfortable being matched within one year of age.')),
                ('prefers_shared_rso', models.BooleanField(default=False, help_text='Screen 4: weight shared RSO membership more heavily.')),
                ('open_to_other_departments', models.BooleanField(default=True, help_text='Screen 4: willing to meet students outside their college.')),
                ('is_sso_verified', models.BooleanField(default=True, help_text='False removes the student from the weekly matching pool.')),
                ('onboarding_completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('interests', models.ManyToManyField(blank=True, related_name='profiles', through='connect.ProfileInterest', to='connect.interest')),
                ('user', models.OneToOneField(help_text='Account created by UIUC SSO sign-in.', on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student profile',
                'ordering': ['full_name', 'net_id'],
            },
        ),
        migrations.AddField(
            model_name='profileinterest',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interest_links', to='connect.studentprofile'),
        ),
        migrations.AddField(
            model_name='matchparticipant',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='match_participations', to='connect.studentprofile'),
        ),
        migrations.CreateModel(
            name='AvailabilitySlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(6, 'Saturday'), (7, 'Sunday')])),
                ('time_block', models.CharField(choices=[('10-12', '10 AM - 12 PM'), ('12-14', '12 - 2 PM'), ('14-16', '2 - 4 PM'), ('16-18', '4 - 6 PM')], max_length=5)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_slots', to='connect.studentprofile')),
            ],
            options={
                'verbose_name': 'Availability slot',
                'ordering': ['profile', 'weekday', 'time_block'],
            },
        ),
        migrations.AddConstraint(
            model_name='studentprofile',
            constraint=models.UniqueConstraint(fields=('net_id', 'illinois_email'), name='uniq_profile_netid_email'),
        ),
        migrations.AddConstraint(
            model_name='profileinterest',
            constraint=models.UniqueConstraint(fields=('profile', 'interest'), name='uniq_interest_per_profile'),
        ),
        migrations.AddConstraint(
            model_name='matchparticipant',
            constraint=models.UniqueConstraint(fields=('match', 'profile'), name='uniq_participant_per_match'),
        ),
        migrations.AddConstraint(
            model_name='availabilityslot',
            constraint=models.UniqueConstraint(fields=('profile', 'weekday', 'time_block'), name='uniq_slot_per_profile_day_block'),
        ),
    ]
